name: Feature Request
description: Suggest an idea, a feature you want added, a mod to add or a direction in which the pack should go
labels: enhancement
body:
  - type: dropdown
    id: request_category
    attributes:
      label: Request Category
      description: "Chose an option below to help us already know what kind of feature request this is"
      options:
        - "Mod Addition"
        - "Core Change"
        - "Processing Line Addition"
        - "New Multiblock/machine"
        - "Balance Change"
    validations:
      required: true
  - type: textarea
    id: idea_description 
    attributes:
      label: Idea Description
      description: "Describe your idea without going in technical details at all, just explain what the idea is and why you want it"
    validations:
      required: true
  - type: textarea
    id: technical
    attributes:
      label: Technical
      description: Give a technical idea of how that could be achieved
      placeholder: "Example: Add this mod, make a script, modifiy this core mod."
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives You've Considered"
      description: "What alternatives have you considered that might help solve the problem? If you aren't sure, or this is not related to a problem, please leave this field blank."
      placeholder: "Example: Otherwise, we can also do Z..."
    validations:
      required: false
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: "Add any other context or screenshots about the feature request here. If you are suggesting a mod, please also add a link to the mod's CurseForge page."
      placeholder: "Example: This main motive for this idea is because X..."
    validations:
      required: false
